---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencost
  namespace: opencost
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip #external dns will create record
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:177398540612:certificate/c10a2f5c-289a-4a21-997c-809a54382aa2
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: 2-app
spec:
  ingressClassName: alb
  rules:
    - host: api.cmcloudlab1629.info
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: opencost
                port:
                  number: 9090
